"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _AudioLayout:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AudioLayoutEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AudioLayout.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AUDIO_LAYOUT_UNSPECIFIED: _AudioLayout.ValueType  # 0
    AUDIO_LAYOUT_STEREO: _AudioLayout.ValueType  # 1
    AUDIO_LAYOUT_MONO: _AudioLayout.ValueType  # 2

class AudioLayout(_AudioLayout, metaclass=_AudioLayoutEnumTypeWrapper): ...

AUDIO_LAYOUT_UNSPECIFIED: AudioLayout.ValueType  # 0
AUDIO_LAYOUT_STEREO: AudioLayout.ValueType  # 1
AUDIO_LAYOUT_MONO: AudioLayout.ValueType  # 2
Global___AudioLayout: _TypeAlias = AudioLayout  # noqa: Y015

class _AudioFormat:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AudioFormatEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AudioFormat.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AUDIO_FORMAT_UNSPECIFIED: _AudioFormat.ValueType  # 0
    AUDIO_FORMAT_OPUS: _AudioFormat.ValueType  # 1
    AUDIO_FORMAT_WAV: _AudioFormat.ValueType  # 2

class AudioFormat(_AudioFormat, metaclass=_AudioFormatEnumTypeWrapper): ...

AUDIO_FORMAT_UNSPECIFIED: AudioFormat.ValueType  # 0
AUDIO_FORMAT_OPUS: AudioFormat.ValueType  # 1
AUDIO_FORMAT_WAV: AudioFormat.ValueType  # 2
Global___AudioFormat: _TypeAlias = AudioFormat  # noqa: Y015

class _ToolResultMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ToolResultModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ToolResultMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TOOL_RESULT_MODE_UNSPECIFIED: _ToolResultMode.ValueType  # 0
    TOOL_RESULT_MODE_SUMMARIZE: _ToolResultMode.ValueType  # 1
    """LLM summarize long tool output (uses global tool_summarizer gate)."""
    TOOL_RESULT_MODE_TRUNCATE: _ToolResultMode.ValueType  # 2
    """Deterministically truncate tool output to runtime hard cap."""
    TOOL_RESULT_MODE_NONE: _ToolResultMode.ValueType  # 3
    """Keep raw tool output as-is (no summarize, no truncate)."""

class ToolResultMode(_ToolResultMode, metaclass=_ToolResultModeEnumTypeWrapper):
    """Per-tool output handling mode after execution."""

TOOL_RESULT_MODE_UNSPECIFIED: ToolResultMode.ValueType  # 0
TOOL_RESULT_MODE_SUMMARIZE: ToolResultMode.ValueType  # 1
"""LLM summarize long tool output (uses global tool_summarizer gate)."""
TOOL_RESULT_MODE_TRUNCATE: ToolResultMode.ValueType  # 2
"""Deterministically truncate tool output to runtime hard cap."""
TOOL_RESULT_MODE_NONE: ToolResultMode.ValueType  # 3
"""Keep raw tool output as-is (no summarize, no truncate)."""
Global___ToolResultMode: _TypeAlias = ToolResultMode  # noqa: Y015

@_typing.final
class RecordingConfig(_message.Message):
    """Session recording configuration"""

    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    OUTPUT_URI_FIELD_NUMBER: _builtins.int
    AUDIO_LAYOUT_FIELD_NUMBER: _builtins.int
    SAMPLE_RATE_FIELD_NUMBER: _builtins.int
    AUDIO_FORMAT_FIELD_NUMBER: _builtins.int
    MAX_DURATION_SECS_FIELD_NUMBER: _builtins.int
    SAVE_TRANSCRIPT_FIELD_NUMBER: _builtins.int
    INCLUDE_TOOL_DETAILS_FIELD_NUMBER: _builtins.int
    INCLUDE_LLM_METADATA_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    output_uri: _builtins.str
    audio_layout: Global___AudioLayout.ValueType
    sample_rate: _builtins.int
    audio_format: Global___AudioFormat.ValueType
    max_duration_secs: _builtins.int
    save_transcript: _builtins.bool
    include_tool_details: _builtins.bool
    include_llm_metadata: _builtins.bool
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        output_uri: _builtins.str = ...,
        audio_layout: Global___AudioLayout.ValueType = ...,
        sample_rate: _builtins.int = ...,
        audio_format: Global___AudioFormat.ValueType = ...,
        max_duration_secs: _builtins.int = ...,
        save_transcript: _builtins.bool = ...,
        include_tool_details: _builtins.bool = ...,
        include_llm_metadata: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio_format", b"audio_format", "audio_layout", b"audio_layout", "enabled", b"enabled", "include_llm_metadata", b"include_llm_metadata", "include_tool_details", b"include_tool_details", "max_duration_secs", b"max_duration_secs", "output_uri", b"output_uri", "sample_rate", b"sample_rate", "save_transcript", b"save_transcript"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RecordingConfig: _TypeAlias = RecordingConfig  # noqa: Y015

@_typing.final
class ParamDef(_message.Message):
    """Tool parameter definition"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    REQUIRED_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    type: _builtins.str
    """e.g., "string", "integer", "boolean" """
    description: _builtins.str
    required: _builtins.bool
    @_builtins.property
    def options(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Valid values for enum types"""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        type: _builtins.str = ...,
        description: _builtins.str = ...,
        required: _builtins.bool = ...,
        options: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "name", b"name", "options", b"options", "required", b"required", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ParamDef: _TypeAlias = ParamDef  # noqa: Y015

@_typing.final
class ToolDef(_message.Message):
    """A tool definition (always a JS script)"""

    DESCRIPTOR: _descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: _builtins.int
    SCRIPT_FIELD_NUMBER: _builtins.int
    PARAMS_FIELD_NUMBER: _builtins.int
    CANCEL_ON_BARGE_IN_FIELD_NUMBER: _builtins.int
    SIDE_EFFECT_FIELD_NUMBER: _builtins.int
    RESULT_MODE_FIELD_NUMBER: _builtins.int
    description: _builtins.str
    script: _builtins.str
    cancel_on_barge_in: _builtins.bool
    """If true (default), barge-in drops the tool result"""
    side_effect: _builtins.bool
    """If true, this tool has side effects"""
    result_mode: Global___ToolResultMode.ValueType
    """Optional post-tool output handling mode.
    If UNSPECIFIED, runtime falls back to global config behavior.
    """
    @_builtins.property
    def params(self) -> _containers.RepeatedCompositeFieldContainer[Global___ParamDef]: ...
    def __init__(
        self,
        *,
        description: _builtins.str = ...,
        script: _builtins.str = ...,
        params: _abc.Iterable[Global___ParamDef] | None = ...,
        cancel_on_barge_in: _builtins.bool = ...,
        side_effect: _builtins.bool = ...,
        result_mode: Global___ToolResultMode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cancel_on_barge_in", b"cancel_on_barge_in", "description", b"description", "params", b"params", "result_mode", b"result_mode", "script", b"script", "side_effect", b"side_effect"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ToolDef: _TypeAlias = ToolDef  # noqa: Y015

@_typing.final
class NodeDef(_message.Message):
    """A single node in the graph"""

    DESCRIPTOR: _descriptor.Descriptor

    SYSTEM_PROMPT_FIELD_NUMBER: _builtins.int
    TOOLS_FIELD_NUMBER: _builtins.int
    EDGES_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    TEMPERATURE_FIELD_NUMBER: _builtins.int
    MAX_TOKENS_FIELD_NUMBER: _builtins.int
    VOICE_ID_FIELD_NUMBER: _builtins.int
    GREETING_FIELD_NUMBER: _builtins.int
    system_prompt: _builtins.str
    model: _builtins.str
    temperature: _builtins.float
    max_tokens: _builtins.int
    voice_id: _builtins.str
    """TTS voice override"""
    greeting: _builtins.str
    @_builtins.property
    def tools(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """keys referencing AgentGraphDef.tools"""

    @_builtins.property
    def edges(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """node IDs this node can transfer to"""

    def __init__(
        self,
        *,
        system_prompt: _builtins.str = ...,
        tools: _abc.Iterable[_builtins.str] | None = ...,
        edges: _abc.Iterable[_builtins.str] | None = ...,
        model: _builtins.str | None = ...,
        temperature: _builtins.float | None = ...,
        max_tokens: _builtins.int | None = ...,
        voice_id: _builtins.str | None = ...,
        greeting: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_greeting", b"_greeting", "_max_tokens", b"_max_tokens", "_model", b"_model", "_temperature", b"_temperature", "_voice_id", b"_voice_id", "greeting", b"greeting", "max_tokens", b"max_tokens", "model", b"model", "temperature", b"temperature", "voice_id", b"voice_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_greeting", b"_greeting", "_max_tokens", b"_max_tokens", "_model", b"_model", "_temperature", b"_temperature", "_voice_id", b"_voice_id", "edges", b"edges", "greeting", b"greeting", "max_tokens", b"max_tokens", "model", b"model", "system_prompt", b"system_prompt", "temperature", b"temperature", "tools", b"tools", "voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__greeting: _TypeAlias = _typing.Literal["greeting"]  # noqa: Y015
    _WhichOneofArgType__greeting: _TypeAlias = _typing.Literal["_greeting", b"_greeting"]  # noqa: Y015
    _WhichOneofReturnType__max_tokens: _TypeAlias = _typing.Literal["max_tokens"]  # noqa: Y015
    _WhichOneofArgType__max_tokens: _TypeAlias = _typing.Literal["_max_tokens", b"_max_tokens"]  # noqa: Y015
    _WhichOneofReturnType__model: _TypeAlias = _typing.Literal["model"]  # noqa: Y015
    _WhichOneofArgType__model: _TypeAlias = _typing.Literal["_model", b"_model"]  # noqa: Y015
    _WhichOneofReturnType__temperature: _TypeAlias = _typing.Literal["temperature"]  # noqa: Y015
    _WhichOneofArgType__temperature: _TypeAlias = _typing.Literal["_temperature", b"_temperature"]  # noqa: Y015
    _WhichOneofReturnType__voice_id: _TypeAlias = _typing.Literal["voice_id"]  # noqa: Y015
    _WhichOneofArgType__voice_id: _TypeAlias = _typing.Literal["_voice_id", b"_voice_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__greeting) -> _WhichOneofReturnType__greeting | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__max_tokens) -> _WhichOneofReturnType__max_tokens | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__model) -> _WhichOneofReturnType__model | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__temperature) -> _WhichOneofReturnType__temperature | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__voice_id) -> _WhichOneofReturnType__voice_id | None: ...

Global___NodeDef: _TypeAlias = NodeDef  # noqa: Y015

@_typing.final
class AgentGraphDef(_message.Message):
    """A complete agent graph"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class NodesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___NodeDef: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___NodeDef | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ToolsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___ToolDef: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___ToolDef | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ENTRY_FIELD_NUMBER: _builtins.int
    NODES_FIELD_NUMBER: _builtins.int
    TOOLS_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    TIMEZONE_FIELD_NUMBER: _builtins.int
    VOICE_ID_FIELD_NUMBER: _builtins.int
    TTS_PROVIDER_FIELD_NUMBER: _builtins.int
    TTS_MODEL_FIELD_NUMBER: _builtins.int
    RECORDING_FIELD_NUMBER: _builtins.int
    CONFIG_SCHEMA_VERSION_FIELD_NUMBER: _builtins.int
    GEMINI_LIVE_MODEL_FIELD_NUMBER: _builtins.int
    entry: _builtins.str
    """The ID of the node to start with"""
    language: _builtins.str
    """-- Agent-wide settings --
    ISO 639-1
    """
    timezone: _builtins.str
    """IANA timezone"""
    voice_id: _builtins.str
    """Default TTS voice ID"""
    tts_provider: _builtins.str
    """e.g. "elevenlabs" """
    tts_model: _builtins.str
    """e.g. "eleven_turbo_v2" """
    config_schema_version: _builtins.str
    """Envelope field for versions (e.g. "v3_graph")"""
    gemini_live_model: _builtins.str
    """-- Native multimodal (Gemini Live) --
    When set, the session bypasses STT/LLM/TTS and uses Gemini Live's native
    bidirectional audio-to-audio WebSocket for the entire conversation.
    """
    @_builtins.property
    def nodes(self) -> _containers.MessageMap[_builtins.str, Global___NodeDef]:
        """All nodes keyed by ID"""

    @_builtins.property
    def tools(self) -> _containers.MessageMap[_builtins.str, Global___ToolDef]:
        """All tool definitions keyed by tool name"""

    @_builtins.property
    def recording(self) -> Global___RecordingConfig:
        """Session recording configuration"""

    def __init__(
        self,
        *,
        entry: _builtins.str = ...,
        nodes: _abc.Mapping[_builtins.str, Global___NodeDef] | None = ...,
        tools: _abc.Mapping[_builtins.str, Global___ToolDef] | None = ...,
        language: _builtins.str | None = ...,
        timezone: _builtins.str | None = ...,
        voice_id: _builtins.str | None = ...,
        tts_provider: _builtins.str | None = ...,
        tts_model: _builtins.str | None = ...,
        recording: Global___RecordingConfig | None = ...,
        config_schema_version: _builtins.str | None = ...,
        gemini_live_model: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_config_schema_version", b"_config_schema_version", "_gemini_live_model", b"_gemini_live_model", "_language", b"_language", "_recording", b"_recording", "_timezone", b"_timezone", "_tts_model", b"_tts_model", "_tts_provider", b"_tts_provider", "_voice_id", b"_voice_id", "config_schema_version", b"config_schema_version", "gemini_live_model", b"gemini_live_model", "language", b"language", "recording", b"recording", "timezone", b"timezone", "tts_model", b"tts_model", "tts_provider", b"tts_provider", "voice_id", b"voice_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_config_schema_version", b"_config_schema_version", "_gemini_live_model", b"_gemini_live_model", "_language", b"_language", "_recording", b"_recording", "_timezone", b"_timezone", "_tts_model", b"_tts_model", "_tts_provider", b"_tts_provider", "_voice_id", b"_voice_id", "config_schema_version", b"config_schema_version", "entry", b"entry", "gemini_live_model", b"gemini_live_model", "language", b"language", "nodes", b"nodes", "recording", b"recording", "timezone", b"timezone", "tools", b"tools", "tts_model", b"tts_model", "tts_provider", b"tts_provider", "voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__config_schema_version: _TypeAlias = _typing.Literal["config_schema_version"]  # noqa: Y015
    _WhichOneofArgType__config_schema_version: _TypeAlias = _typing.Literal["_config_schema_version", b"_config_schema_version"]  # noqa: Y015
    _WhichOneofReturnType__gemini_live_model: _TypeAlias = _typing.Literal["gemini_live_model"]  # noqa: Y015
    _WhichOneofArgType__gemini_live_model: _TypeAlias = _typing.Literal["_gemini_live_model", b"_gemini_live_model"]  # noqa: Y015
    _WhichOneofReturnType__language: _TypeAlias = _typing.Literal["language"]  # noqa: Y015
    _WhichOneofArgType__language: _TypeAlias = _typing.Literal["_language", b"_language"]  # noqa: Y015
    _WhichOneofReturnType__recording: _TypeAlias = _typing.Literal["recording"]  # noqa: Y015
    _WhichOneofArgType__recording: _TypeAlias = _typing.Literal["_recording", b"_recording"]  # noqa: Y015
    _WhichOneofReturnType__timezone: _TypeAlias = _typing.Literal["timezone"]  # noqa: Y015
    _WhichOneofArgType__timezone: _TypeAlias = _typing.Literal["_timezone", b"_timezone"]  # noqa: Y015
    _WhichOneofReturnType__tts_model: _TypeAlias = _typing.Literal["tts_model"]  # noqa: Y015
    _WhichOneofArgType__tts_model: _TypeAlias = _typing.Literal["_tts_model", b"_tts_model"]  # noqa: Y015
    _WhichOneofReturnType__tts_provider: _TypeAlias = _typing.Literal["tts_provider"]  # noqa: Y015
    _WhichOneofArgType__tts_provider: _TypeAlias = _typing.Literal["_tts_provider", b"_tts_provider"]  # noqa: Y015
    _WhichOneofReturnType__voice_id: _TypeAlias = _typing.Literal["voice_id"]  # noqa: Y015
    _WhichOneofArgType__voice_id: _TypeAlias = _typing.Literal["_voice_id", b"_voice_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__config_schema_version) -> _WhichOneofReturnType__config_schema_version | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__gemini_live_model) -> _WhichOneofReturnType__gemini_live_model | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__language) -> _WhichOneofReturnType__language | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__recording) -> _WhichOneofReturnType__recording | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__timezone) -> _WhichOneofReturnType__timezone | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__tts_model) -> _WhichOneofReturnType__tts_model | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__tts_provider) -> _WhichOneofReturnType__tts_provider | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__voice_id) -> _WhichOneofReturnType__voice_id | None: ...

Global___AgentGraphDef: _TypeAlias = AgentGraphDef  # noqa: Y015
